const codes = {
  R:{thai:'Realistic',name:'นักปฏิบัติ',short:'ลงมือทำ ชอบของจริง',color:'R',icon:'⚙️',description:'เป็นคนที่เรียนรู้ได้ดีเมื่อได้ลงมือทำจริง สนใจเครื่องมือ เครื่องจักร เทคโนโลยี งานกลางแจ้ง หรือการแก้ปัญหาที่จับต้องได้',strengths:['ใช้เครื่องมือและเทคโนโลยี','แก้ปัญหาเฉพาะหน้า','อดทนและเป็นระบบ'],environment:'งานช่าง วิศวกรรม เกษตร อุตสาหกรรม ความปลอดภัย และงานเทคนิค'},
  I:{thai:'Investigative',name:'นักคิดวิเคราะห์',short:'สงสัย ค้นคว้า เข้าใจลึก',color:'I',icon:'🔎',description:'ชอบตั้งคำถาม ค้นหาคำอธิบาย และใช้เหตุผล สนุกกับข้อมูล การทดลอง วิทยาศาสตร์ และการแก้โจทย์ที่ซับซ้อน',strengths:['คิดเชิงตรรกะ','วิเคราะห์ข้อมูล','เรียนรู้ด้วยตนเอง'],environment:'วิทยาศาสตร์ สุขภาพ วิจัย ข้อมูล เทคโนโลยี และห้องปฏิบัติการ'},
  A:{thai:'Artistic',name:'นักสร้างสรรค์',short:'จินตนาการ ถ่ายทอดตัวตน',color:'A',icon:'✦',description:'ให้ความสำคัญกับจินตนาการ ความงาม และการสื่อสารความคิด ชอบออกแบบ สร้างเรื่องราว ดนตรี ภาษา หรือรูปแบบใหม่ ๆ',strengths:['คิดนอกกรอบ','สื่อสารอารมณ์และความคิด','มองเห็นความงาม'],environment:'ออกแบบ สื่อ ภาพยนตร์ ดนตรี โฆษณา แฟชั่น และคอนเทนต์'},
  S:{thai:'Social',name:'ผู้เข้าใจผู้คน',short:'ช่วยเหลือ รับฟัง เติบโตด้วยกัน',color:'S',icon:'♡',description:'สนใจผู้คนและการพัฒนาผู้อื่น รู้สึกมีพลังเมื่อได้ช่วยสอน ดูแล รับฟัง หรือทำงานร่วมกับคนหลายกลุ่ม',strengths:['เห็นอกเห็นใจ','สื่อสารและประสานงาน','ส่งเสริมผู้อื่น'],environment:'การศึกษา สุขภาพ จิตวิทยา สังคมสงเคราะห์ การบริการ และชุมชน'},
  E:{thai:'Enterprising',name:'ผู้นำการเปลี่ยนแปลง',short:'กล้าตัดสินใจ ชวนคนไปต่อ',color:'E',icon:'↗',description:'ชอบริเริ่ม ชักชวน และเปลี่ยนไอเดียให้เกิดขึ้นจริง สนุกกับเป้าหมาย การโน้มน้าว การเจรจา ธุรกิจ และการนำทีม',strengths:['ตัดสินใจและริเริ่ม','โน้มน้าวใจ','มองเห็นโอกาส'],environment:'ธุรกิจ การตลาด การขาย ผู้ประกอบการ การจัดการ และกฎหมาย'},
  C:{thai:'Conventional',name:'ผู้จัดระบบ',short:'ละเอียด รอบคอบ ไว้ใจได้',color:'C',icon:'▦',description:'ชอบความชัดเจนและการจัดระเบียบ ทำงานกับรายละเอียด ข้อมูล ตัวเลข และขั้นตอนอย่างรอบคอบ เพื่อให้งานเดินหน้าได้อย่างถูกต้อง',strengths:['จัดระเบียบข้อมูล','ละเอียดและรับผิดชอบ','วางแผนตามขั้นตอน'],environment:'บัญชี การเงิน ธุรการ โลจิสติกส์ ข้อมูล สำนักงาน และงานกำกับมาตรฐาน'}
};
const careerIcons={R:'⚙️',I:'🔎',A:'✦',S:'♡',E:'↗',C:'▦'};
function normalizeOccupationText(text){return String(text||'').replace(/([\u0e00-\u0e7f])\s+([่้๊๋]?)า/g,'$1$2ำ')}
const careers=occupationGroups.map((group,i)=>{const lines=group.lines.map(normalizeOccupationText);const occupationText=lines.join(' ');return {id:i+1,name:`อาชีพตามรหัส ${group.code}`,code:group.code,desc:lines[0],icon:careerIcons[group.code[0]]||'✦',faculty:'รายชื่ออาชีพตามรหัสของ จอห์น แอล ฮอลแลนด์',occupationText}});
const questions = [
 ['กิจกรรม','ประกอบหรือซ่อมสิ่งของที่มีชิ้นส่วน'],['กิจกรรม','ทดลอง ค้นคว้า หรือหาคำตอบจากข้อมูล'],['กิจกรรม','วาดภาพ ออกแบบ หรือสร้างผลงาน'],['กิจกรรม','สอน อธิบาย หรือช่วยคนแก้ปัญหา'],['กิจกรรม','ชวนคนเห็นด้วยกับไอเดียของคุณ'],['กิจกรรม','จัดแฟ้ม ข้อมูล หรือรายการให้เป็นระเบียบ'],
 ['ความสามารถ','ใช้เครื่องมือหรืออุปกรณ์ได้อย่างคล่องแคล่ว'],['ความสามารถ','วิเคราะห์โจทย์ที่มีเหตุผลหลายขั้นตอน'],['ความสามารถ','คิดไอเดียหรือวิธีนำเสนอแปลกใหม่'],['ความสามารถ','รับฟังความรู้สึกและสื่อสารกับคนอื่น'],['ความสามารถ','วางเป้าหมายและพาคนอื่นทำงานให้สำเร็จ'],['ความสามารถ','ตรวจรายละเอียด ตัวเลข หรือเอกสารได้รอบคอบ'],
 ['อาชีพ','สนใจอาชีพที่ได้ทำงานกับเครื่องมือ เทคโนโลยี หรือภาคสนาม'],['อาชีพ','สนใจอาชีพนักวิทยาศาสตร์ นักวิจัย หรือผู้เชี่ยวชาญ'],['อาชีพ','สนใจอาชีพนักออกแบบ นักเขียน หรือผู้สร้างสื่อ'],['อาชีพ','สนใจอาชีพครู บุคลากรสุขภาพ หรือผู้ให้คำปรึกษา'],['อาชีพ','สนใจอาชีพนักธุรกิจ นักการตลาด หรือผู้นำโครงการ'],['อาชีพ','สนใจอาชีพบัญชี การเงิน ธุรการ หรือวางระบบข้อมูล']
];
let expandedQuestions=[];
const resources=[
 ['🎓','MyTCAS · ค้นหาหลักสูตร','ค้นหามหาวิทยาลัย คณะ และหลักสูตร TCAS','https://course.mytcas.com/'],['⌂','ที่ประชุมอธิการบดีแห่งประเทศไทย','ข้อมูลการรับสมัครและระบบ TCAS','https://www.mytcas.com/'],['▤','กระทรวงแรงงาน','ข่าว บริการ และข้อมูลด้านแรงงานไทย','https://www.mol.go.th/'],['↗','กรมการจัดหางาน','บริการหางานและข้อมูลตลาดแรงงาน','https://www.doe.go.th/'],['◉','JobThai','ค้นหางานและฝึกงานในประเทศไทย','https://www.jobthai.com/'],['⌁','JobsDB Thailand','ตำแหน่งงานและคำแนะนำด้านอาชีพ','https://th.jobsdb.com/'],['▦','JOBBKK','ค้นหางานและสร้างเรซูเม่','https://www.jobbkk.com/'],['✦','JobTH','รวมตำแหน่งงานทั่วประเทศไทย','https://www.jobth.com/']
];
let quizIndex=0, answers=[], studentProfile={}, isSubmittingResult=false;
const $=s=>document.querySelector(s);
function normalizeCareerText(text){return String(text||'').toLocaleLowerCase('th-TH').replace(/\s+/g,'').replace(/[^\p{L}\p{N}]+/gu,'')}
function escapeHtml(text){return String(text||'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]))}
const riasecOrder=Object.keys(codes);
const tieBreakSections=['occupations','competencies','activities','selfEstimates'];
function normalizeQuestionSection(type){const value=String(type||'').toLocaleLowerCase('th-TH');if(/อาชีพ|occupation/.test(value))return 'occupations';if(/ความสามารถ|competenc|ability|skill/.test(value))return 'competencies';if(/ประเมินตนเอง|self.?estimate/.test(value))return 'selfEstimates';if(/กิจกรรม|activit/.test(value))return 'activities';return null}
function createSectionScores(){return Object.fromEntries(tieBreakSections.map(section=>[section,Object.fromEntries(riasecOrder.map(code=>[code,0]))]))}
function compareScoreEntries(a,b){if(b.score!==a.score)return b.score-a.score;for(const section of tieBreakSections){if(b.sectionScores[section]!==a.sectionScores[section])return b.sectionScores[section]-a.sectionScores[section]}return riasecOrder.indexOf(a.code)-riasecOrder.indexOf(b.code)}
function sameTieGroup(a,b){return a.score===b.score&&tieBreakSections.every(section=>a.sectionScores[section]===b.sectionScores[section])}
function permutations(items){if(items.length<2)return [items];return items.flatMap((item,index)=>permutations([...items.slice(0,index),...items.slice(index+1)]).map(rest=>[item,...rest]))}
function buildPotentialCodes(ranking){const topFour=ranking.slice(0,4);return [[0,1,2],[0,1,3],[0,2,3],[1,2,3]].map(indexes=>indexes.map(index=>topFour[index].code).join(''))}
function calculateRiasecResult(questionList,answerList){const scores=Object.fromEntries(riasecOrder.map(code=>[code,0]));const sectionScores=createSectionScores();questionList.forEach((question,index)=>{const code=String(question.code||'').toUpperCase();if(!riasecOrder.includes(code))return;const value=Math.max(0,Number(answerList[index])||0);scores[code]+=value;const section=normalizeQuestionSection(question.type);if(section)sectionScores[section][code]+=value});const ranking=riasecOrder.map(code=>({code,score:scores[code],sectionScores:tieBreakSections.reduce((result,section)=>{result[section]=sectionScores[section][code];return result},{})})).sort(compareScoreEntries);const tieBlocks=[];for(let index=0;index<ranking.length;){let end=index+1;while(end<ranking.length&&sameTieGroup(ranking[index],ranking[end]))end++;tieBlocks.push(ranking.slice(index,end));index=end}let rankingVariants=[[]];for(const block of tieBlocks){const blockOrders=block.length>1?permutations(block):[block];rankingVariants=rankingVariants.flatMap(prefix=>blockOrders.map(order=>[...prefix,...order])).slice(0,120)}const alternativeCodes=[...new Set(rankingVariants.map(order=>order.slice(0,3).map(entry=>entry.code).join('')))];const summaryCode=ranking.slice(0,3).map(entry=>entry.code).join('');return {scores,sectionScores,ranking,summaryCode,potentialCodes:buildPotentialCodes(ranking),alternativeCodes:alternativeCodes.filter(code=>code!==summaryCode).slice(0,6)}}
const careerSignals=[
  {terms:['แพทย์','หมอ','ทันตแพทย์','สัตวแพทย์'],codes:['I','S']},{terms:['พยาบาล','กายภาพบำบัด','นักบำบัด','สาธารณสุข'],codes:['S','I']},
  {terms:['วิทยาศาสตร์','นักวิจัย','วิจัย','นักวิเคราะห์','data','ดาต้า','โปรแกรมเมอร์','developer','software','ซอฟต์แวร์','ไอที','คอมพิวเตอร์','เภสัช'],codes:['I']},
  {terms:['วิศวกร','ช่าง','เทคนิค','เกษตร','ทหาร','ตำรวจ','นักบิน','โลจิสติกส์','นักกีฬา'],codes:['R']},{terms:['สถาปนิก'],codes:['A','R']},
  {terms:['ศิลปิน','ออกแบบ','ดีไซน์','กราฟิก','นักเขียน','ดนตรี','นักร้อง','นักแสดง','ช่างภาพ','ครีเอเตอร์','creator','ยูทูบ','content','คอนเทนต์','แฟชั่น','เชฟ'],codes:['A']},
  {terms:['ครู','อาจารย์','ติวเตอร์','นักจิตวิทยา','ที่ปรึกษา','สังคมสงเคราะห์','ทรัพยากรบุคคล','hr','โค้ช'],codes:['S']},
  {terms:['นักธุรกิจ','ผู้ประกอบการ','การตลาด','นักขาย','เซลส์','sales','ผู้จัดการ','ผู้บริหาร','ทนาย','นักการเมือง','นายหน้า','อินฟลูเอนเซอร์'],codes:['E']},
  {terms:['บัญชี','การเงิน','ธนาคาร','ธุรการ','เลขานุการ','ผู้ตรวจสอบ','auditor','แอดมิน','admin','ภาษี','จัดซื้อ'],codes:['C']}
];
function inferCareerCodes(occupation){const input=normalizeCareerText(occupation);const matched=careerSignals.flatMap(signal=>signal.terms.some(term=>input.includes(normalizeCareerText(term)))?signal.codes:[]);return [...new Set(matched)].slice(0,3)}
function formatRiasecCodes(list){return list.map(code=>`หมวด ${code}`).join(', ')}
function assessOccupationFits(occupations,result){const competencyScores=result.sectionScores.competencies;const totalRank=Object.fromEntries(result.ranking.map((entry,index)=>[entry.code,index]));const abilityRanking=riasecOrder.map(code=>({code,score:competencyScores[code]})).sort((a,b)=>b.score-a.score||totalRank[a.code]-totalRank[b.code]);const abilityPosition=Object.fromEntries(abilityRanking.map((entry,index)=>[entry.code,index]));const abilityCodes=abilityRanking.slice(0,3).map(entry=>entry.code);return occupations.map((occupation,index)=>{const careerCodes=inferCareerCodes(occupation);if(!careerCodes.length)return {occupation,index,careerCodes,abilityCodes,status:'unknown',label:'ยังประเมินไม่ได้',detail:'ชื่ออาชีพนี้ยังระบุลักษณะงานไม่ชัดพอ'};if(!abilityRanking[0].score)return {occupation,index,careerCodes,abilityCodes,status:'unknown',label:'ข้อมูลความสามารถยังไม่พอ',detail:`ลักษณะงาน ${formatRiasecCodes(careerCodes)}`};const bestPosition=Math.min(...careerCodes.map(code=>abilityPosition[code]));const status=bestPosition<2?'strong':bestPosition<4?'partial':'explore';const label=status==='strong'?'สอดคล้องมาก':status==='partial'?'สอดคล้องบางส่วน':'ควรพัฒนาความสามารถเพิ่ม';const developmentCodes=careerCodes.filter(code=>abilityPosition[code]>1);const detail=developmentCodes.length?`ลักษณะงาน ${formatRiasecCodes(careerCodes)} · ควรพัฒนา ${formatRiasecCodes(developmentCodes)}`:`สอดคล้องกับ ${formatRiasecCodes(careerCodes)}`;return {occupation,index,careerCodes,abilityCodes,status,label,detail}})}
function renderOccupationFits(groups){return `<div class="career-match-panel"><h3>อาชีพที่กรอกสอดคล้องกับความสามารถหรือไม่</h3><p>ประเมินจากคะแนนหมวดความสามารถของผู้เรียนเป็นหลัก โดยไม่ค้นเทียบชื่ออาชีพจาก PDF</p>${groups.map(group=>`<div class="career-match-group"><strong>อาชีพที่ ${group.index+1}: ${escapeHtml(group.occupation)}</strong><div class="career-match-list"><span class="career-match-tag ${group.status}"><small>${group.label}</small>${escapeHtml(group.detail)}</span></div></div>`).join('')}</div>`}
function renderCodes(){ $('#codeCards').innerHTML=Object.entries(codes).map(([letter,c])=>`<button class="code-card code-${letter}" data-code="${letter}"><span class="code-letter">${letter}</span><strong>${c.name}</strong><small>${c.short}</small></button>`).join(''); document.querySelectorAll('.code-card').forEach(b=>b.onclick=()=>showCode(b.dataset.code)); }
function showCode(letter){const c=codes[letter]; $('#dialogContent').innerHTML=`<p class="detail-code">${letter}</p><h2 class="detail-title">${c.name}<br><small>${c.thai}</small></h2><p class="detail-text">${c.description}</p><h3>จุดแข็งที่มักพบ</h3><ul class="detail-list">${c.strengths.map(x=>`<li>${x}</li>`).join('')}</ul><div class="detail-callout"><strong>สภาพแวดล้อมที่เหมาะ:</strong> ${c.environment}</div>`; $('#detailDialog').showModal();}
function renderCareers(filter='ALL',search=''){const query=normalizeCareerText(search);const list=careers.filter(c=>(filter==='ALL'||c.code.includes(filter))&&(!query||normalizeCareerText(`${c.code} ${c.name} ${c.occupationText}`).includes(query))); $('#careerGrid').innerHTML=list.length?list.map(c=>`<article class="career-card" data-career="${c.id}"><div class="career-meta"><span class="career-code">${c.code}</span><span class="career-icon">${c.icon}</span></div><h3>${c.name}</h3><p>${c.desc}…</p><span class="career-more">ดูรายชื่ออาชีพทั้งหมดในรหัสนี้ →</span></article>`).join(''):'<p class="career-empty">ยังไม่พบอาชีพที่ตรงหรือใกล้เคียงในรายการ</p>'; document.querySelectorAll('.career-card').forEach(x=>x.onclick=()=>showCareer(+x.dataset.career));}
function showCareer(id){const c=careers.find(x=>x.id===id);$('#dialogContent').innerHTML=`<p class="detail-code">${c.code}</p><h2 class="detail-title">${c.icon} ${c.name}</h2><p class="detail-text">${escapeHtml(c.occupationText)}</p><div class="detail-callout"><strong>แหล่งข้อมูล</strong><br>${c.faculty}</div><p class="detail-text">ใช้รหัสนี้เป็นแนวทางสำรวจอาชีพและค้นหาหลักสูตรที่เกี่ยวข้องใน MyTCAS</p><a class="dialog-link" href="https://course.mytcas.com/" target="_blank" rel="noopener">ค้นหาหลักสูตรใน MyTCAS →</a>`;$('#detailDialog').showModal();}
function exactCareerGuide(query){const normalized=normalizeCareerGuideText(query);return careerGuides.find(guide=>[guide.name,...guide.aliases].some(term=>normalizeCareerGuideText(term)===normalized))}
function buildOfficialCareerGuide(occupation){const group=careerGroupGuides[occupation.group];return {name:occupation.name,icon:group.icon,code:`หมวด ${occupation.group}`,summary:`${occupation.name} ${group.summary}`,work:[`ทำงานตามขอบเขตหน้าที่ของ “${occupation.name}”`,...group.work],study:group.study,skills:group.skills,source:occupation.source,groupName:thaiOccupationGroups[occupation.group-1]}}
function resolveCareerGuide(query){const curatedExact=exactCareerGuide(query);if(curatedExact)return curatedExact;const officialMatches=findThaiOccupations(query,1);if(officialMatches[0]&&normalizeThaiOccupationText(officialMatches[0].name)===normalizeThaiOccupationText(query))return buildOfficialCareerGuide(officialMatches[0]);const curatedMatches=findCareerGuides(query,1);return curatedMatches[0]||officialMatches[0]&&buildOfficialCareerGuide(officialMatches[0])}
function renderCareerGuide(guide){if(!guide){$('#careerGuideResult').innerHTML='<div class="career-guide-empty"><strong>ยังไม่พบชื่อนี้ในบัญชีอาชีพทางการ</strong><br>ลองใช้ชื่อเรียกที่กว้างขึ้น หรือตรวจการสะกดจากคำแนะนำด้านบน</div>';return}const block=(title,items)=>`<section class="career-guide-block"><h4>${title}</h4><ul>${items.map(item=>`<li>${escapeHtml(item)}</li>`).join('')}</ul></section>`;const official=guide.source?`<div class="career-official"><strong>ข้อมูลภาพรวมตาม ${escapeHtml(guide.groupName)}</strong><a href="${guide.source}" target="_blank" rel="noopener">เปิดเอกสารอาชีพจากกรมการจัดหางาน →</a></div>`:'';$('#careerGuideResult').innerHTML=`<article class="career-guide-card"><div class="career-guide-head"><span class="career-guide-icon">${guide.icon}</span><div><h3>${escapeHtml(guide.name)}</h3><p>${escapeHtml(guide.summary)}</p></div><span class="career-guide-code">${guide.code}</span></div><div class="career-guide-columns">${block('ทำงานอะไรบ้าง',guide.work)}${block('ต้องเรียนอะไร',guide.study)}${block('ทักษะที่ควรเริ่มฝึก',guide.skills)}</div>${official}<p class="career-guide-note">เส้นทางการเรียนเป็นภาพรวม คุณสมบัติและเกณฑ์รับสมัครอาจต่างกันในแต่ละปีและแต่ละสถาบัน ควรตรวจสอบหลักสูตรล่าสุดใน MyTCAS และหน่วยงานวิชาชีพที่เกี่ยวข้องอีกครั้ง</p></article>`}
function renderCareerSuggestions(query=''){const popular=careerGuides.filter(guide=>['แพทย์','ครู','วิศวกร','นักพัฒนาซอฟต์แวร์','นักออกแบบกราฟิก'].includes(guide.name));const candidates=query?[...findCareerGuides(query,8),...findThaiOccupations(query,12).map(occupation=>({name:occupation.name,icon:careerGroupGuides[occupation.group].icon}))]:popular;const seen=new Set();const suggestions=candidates.filter(item=>{const key=normalizeCareerGuideText(item.name);if(seen.has(key))return false;seen.add(key);return true}).slice(0,8);$('#careerSuggestions').innerHTML=suggestions.map(guide=>`<button type="button" class="career-suggestion" data-guide-name="${escapeHtml(guide.name)}">${guide.icon} ${escapeHtml(guide.name)}</button>`).join('');document.querySelectorAll('.career-suggestion').forEach(button=>button.onclick=()=>{$('#careerGuideSearch').value=button.dataset.guideName;searchCareerGuide()})}
function searchCareerGuide(){const query=$('#careerGuideSearch').value.trim();if(!query){$('#careerGuideResult').innerHTML='';renderCareerSuggestions();return}renderCareerGuide(resolveCareerGuide(query));renderCareerSuggestions(query)}
function renderFilters(){const all=['ALL',...Object.keys(codes)]; $('#careerFilters').innerHTML=all.map((x,i)=>`<button class="filter ${i===0?'active':''}" data-filter="${x}">${x==='ALL'?'ทั้งหมด':x+' · '+codes[x].name}</button>`).join('');document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelector('.filter.active').classList.remove('active');b.classList.add('active');renderCareers(b.dataset.filter,$('#careerSearch').value)});}
function renderLinks(){$('#linkList').innerHTML=resources.map(r=>`<a class="resource-link" href="${r[3]}" target="_blank" rel="noopener"><span class="resource-icon">${r[0]}</span><div><strong>${r[1]}</strong><small>${r[2]}</small></div><span>→</span></a>`).join('')}
function showQuestion(){const q=expandedQuestions[quizIndex];$('#questionType').textContent=q.type;$('#progressLabel').textContent=`${quizIndex+1} / ${expandedQuestions.length}`;$('#progressBar').style.width=`${(quizIndex+1)/expandedQuestions.length*100}%`;$('#questionText').textContent=q.text;$('#questionHelp').textContent=`เลือก “${q.positive}” เมื่อข้อความนี้ตรงกับคุณ`;document.querySelector('.answer.no').textContent=q.negative;document.querySelector('.answer.yes').textContent=q.positive;$('#backQuestion').style.visibility=quizIndex?'visible':'hidden'}
function answer(v){if(isSubmittingResult)return;answers[quizIndex]=v;if(quizIndex<expandedQuestions.length-1){quizIndex++;showQuestion()}else{isSubmittingResult=true;document.querySelectorAll('.answer').forEach(button=>button.disabled=true);showResults()}}
async function showResults(){const result=calculateRiasecResult(expandedQuestions,answers);const {scores,ranking,summaryCode}=result;const max=Math.max(...Object.values(scores),1);const occupationGroups=assessOccupationFits(studentProfile.occupations,result);const occupationMatches=renderOccupationFits(occupationGroups);const tieNote=result.alternativeCodes.length?`<p class="form-message">กรณีคะแนนและคะแนนย่อยเสมอกัน รหัสทางเลือก: ${result.alternativeCodes.join(', ')}</p>`:'';$('#quizForm').hidden=true;$('#quizResult').hidden=false;$('#quizResult').innerHTML=`<p class="eyebrow">ผลลัพธ์ของคุณ</p><div class="result-code">${summaryCode}</div><p><strong>${codes[summaryCode[0]].name} · ${codes[summaryCode[1]].name} · ${codes[summaryCode[2]].name}</strong></p><div class="result-code-options"><span>รหัส 3 ตัวอักษรที่เป็นไปได้จากคะแนน 4 อันดับแรก</span><div>${result.potentialCodes.map((code,index)=>`<b>${index+1}. ${code}</b>`).join('')}</div></div><div class="result-summary">จุดเด่นของคุณโน้มไปทาง <b>${codes[summaryCode[0]].name}</b> ผสานกับ ${codes[summaryCode[1]].name} และ ${codes[summaryCode[2]].name} ลองดูอาชีพที่ใช้รหัสเหล่านี้เป็นจุดตั้งต้น แล้วค่อยสำรวจคณะและประสบการณ์จริงต่อไป</div>${occupationMatches}<div class="result-bars">${ranking.map(({code,score})=>`<div class="result-bar"><b>${code}</b><span><i style="width:${score/max*100}%"></i></span><b>${score}</b></div>`).join('')}</div>${tieNote}<p class="form-message" id="saveStatus">กำลังบันทึกผล…</p><div class="result-actions"><button class="button primary" id="showMatches">ดูอาชีพที่เข้ากัน →</button><button class="button ghost" id="downloadCsv">ส่งออก CSV</button></div>`;$('#showMatches').onclick=()=>{location.hash='careers';const f=document.querySelector(`[data-filter="${summaryCode[0]}"]`);f.click()};$('#downloadCsv').onclick=()=>downloadCsv(result);const occupationMatchData=occupationGroups.map(group=>({rank:group.index+1,occupation:group.occupation,careerCodes:group.careerCodes,abilityCodes:group.abilityCodes,status:group.status,label:group.label,detail:group.detail}));const payload={student:studentProfile,answers,scores,sectionScores:result.sectionScores,ranking:result.ranking,code:summaryCode,summaryCode,potentialCodes:result.potentialCodes,alternativeCodes:result.alternativeCodes,occupationMatches:occupationMatchData,submittedAt:new Date().toISOString()};localStorage.setItem('riasecResult',JSON.stringify(payload));try{await saveResult(payload);$('#saveStatus').textContent='บันทึกผลลง Google Sheet แล้ว';}catch(error){$('#saveStatus').textContent='บันทึกผลในเครื่องแล้ว กรุณาแจ้งครูหากข้อความนี้ไม่เปลี่ยนเป็น “บันทึกผลลง Google Sheet แล้ว”';}}
async function getQuestions(){const api=window.SDS_CONFIG?.apiUrl;if(!api)throw new Error('ยังไม่ได้ตั้งค่า Apps Script URL');const response=await fetch(`${api}?action=questions`,{cache:'no-store'});const data=await response.json();if(!Array.isArray(data.questions)||data.questions.length!==216)throw new Error('ไม่พบคำถามครบ 216 ข้อ');return data.questions;}
async function saveResult(payload){const api=window.SDS_CONFIG?.apiUrl;if(!api)throw new Error('ยังไม่ได้ตั้งค่า Apps Script URL');return new Promise((resolve,reject)=>{const frame=document.createElement('iframe'),form=document.createElement('form'),input=document.createElement('input'),name=`sds_submit_${Date.now()}`;frame.name=name;frame.hidden=true;form.action=api;form.method='post';form.target=name;form.hidden=true;input.name='payload';input.value=JSON.stringify(payload);form.append(input);document.body.append(frame,form);try{form.submit();window.setTimeout(()=>{frame.remove();form.remove();resolve({ok:true});},1200)}catch(error){frame.remove();form.remove();reject(error)}})}
function downloadCsv(result){const stamp=new Date().toLocaleString('th-TH');const rows=[['วันที่ทำแบบประเมิน',stamp],...studentProfile.occupations.map((occupation,index)=>[`อาชีพที่ ${index+1}`,occupation]),['Holland Code',result.summaryCode],['รหัสที่เป็นไปได้จาก 4 อันดับแรก',result.potentialCodes.join(' | ')],['Alternative Codes',result.alternativeCodes.join(' | ')],...riasecOrder.map(code=>[code,result.scores[code],`กิจกรรม ${result.sectionScores.activities[code]}`,`ความสามารถ ${result.sectionScores.competencies[code]}`,`อาชีพ ${result.sectionScores.occupations[code]}`,`ประเมินตนเอง ${result.sectionScores.selfEstimates[code]}`])];const csvCell=value=>`"${String(value??'').replace(/"/g,'""')}"`;const blob=new Blob(['\ufeff'+rows.map(row=>row.map(csvCell).join(',')).join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`riasec-result-${Date.now()}.csv`;a.click();URL.revokeObjectURL(a.href)}
$('#startQuiz').onclick=async()=>{const required=['firstName','lastName','room','studentNumber'];const gradeNumber=$('#gradeLevel').value.trim();const occupations=Array.from({length:5},(_,i)=>$('#occupation'+(i+1)).value.trim());const missing=required.some(id=>!$('#'+id).value.trim())||!/^[1-6]$/.test(gradeNumber)||occupations.some(value=>!value)||!$('#consent').checked;if(missing){$('#formMessage').textContent='กรุณากรอกชื่อ นามสกุล ระดับชั้นมัธยมศึกษา ห้อง เลขที่ อาชีพให้ครบ 5 อันดับ และยินยอมให้บันทึกข้อมูล';return;}const gradeLevel=`มัธยมศึกษาปีที่ ${gradeNumber}`;studentProfile={firstName:$('#firstName').value.trim(),lastName:$('#lastName').value.trim(),nickName:$('#nickName').value.trim(),gradeLevel,room:$('#room').value.trim(),studentNumber:$('#studentNumber').value.trim(),occupations,consent:true};$('#startQuiz').disabled=true;$('#formMessage').textContent='กำลังเตรียมคำถาม 216 ข้อ…';try{expandedQuestions=await getQuestions();quizIndex=0;answers=[];$('#quizStart').hidden=true;$('#quizForm').hidden=false;showQuestion();}catch(error){$('#formMessage').textContent='ยังเชื่อมระบบคำถามไม่ได้ กรุณาแจ้งครูแนะแนว';console.error(error);}finally{$('#startQuiz').disabled=false;}};document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>answer(+b.dataset.answer));$('#backQuestion').onclick=()=>{if(quizIndex){quizIndex--;showQuestion()}};$('#closeDialog').onclick=()=>$('#detailDialog').close();$('#menuButton').onclick=()=>document.querySelector('nav').classList.toggle('open');
renderCodes();renderFilters();renderCareers();renderLinks();renderCareerSuggestions();
$('#careerSourceSummary').innerHTML=`ค้นหาได้ <strong>${thaiOccupations.length.toLocaleString('th-TH')} อาชีพ</strong> จากข้อมูลการจัดประเภทอาชีพปี 2566 ของกรมการจัดหางาน`;
$('#careerGuideNames').innerHTML=[...new Set([...careerGuides.map(guide=>guide.name),...thaiOccupations.map(occupation=>occupation.name)])].map(name=>`<option value="${escapeHtml(name)}"></option>`).join('');
const careerGuideSearch=$('#careerGuideSearch');careerGuideSearch.oninput=()=>renderCareerSuggestions(careerGuideSearch.value);
const careerSearch=$('#careerSearch');careerSearch.oninput=()=>{const active=document.querySelector('.filter.active');renderCareers(active?.dataset.filter||'ALL',careerSearch.value)};
$('#careerGuideForm').onsubmit=event=>{event.preventDefault();searchCareerGuide()};
